var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                       xx!xx                    ",
   "                                                       xx!xx                    ",
   "  x @                                              o   xx!xx                    ",
   "  xxx                                        o o       xxvxx                    ",
   "  x x                                                                           ",
   "  x x                                       xxxxx                               ",
   "  x xxx                 y                                                   x   ",
   "  x   xxx               y             o o                                   x   ",
   "  x     x            o  y                                                o  x   ",
   "  x  o  x               y            xxxxx                         yy   xx  x   ",
   "  x                xxxxxx                                                   x   ",
   "  x          xxxx  x    x                 s                      xxxxx      x   ",
   "  xxxxxxxxxxxx  xxxx    xxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],

  ["                                                                                                          ",
   "                                                                                                          ",
   "                                                                                                          ",
   "                                                                                     o                    ",
   "                                         o        x               s              xxxxxxxxx                ",
   "                                        xxx       x            xxxxxx            xxxxvxxxx                ",
   "                                x     x           x     xx                                                ",
   "                                x     x                                                                   ",
   "                                x!!!!!x                                                                   ",
   "                      xxx       x!!!!!x           xx    x            x        xxxxx      xxxxxx      x    ",
   "                      xxx     xxx!!!!!xxxx      xxxx    x            x                        x      x    ",
   "                      xxx     xxx!!!!!xxxx     x!!!!!!!!!!x!!!!!!!!!!x     =                  x   o  x    ",
   "            xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxx!!!!!!!!!!x!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ",
   "            xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                  ",
   "            x                                                                                             ",
   "        xxxxx                                                                                             ",
   "       xxx                                                                                                ",
   " @  xxxx                                                                                                   ",
   "xxxxx                                                                                                         "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                             xxxxxxxxxxxxxxxx                                                                 ",
   "                             xxxxxxxvxxxxxxxx                                                              x  ",
   "                             x              x                      o                                       x  ",
   "                             x              x                   xxxxx                                      x  ",
   "                             x              x               o                     o                        x  ",
   "                                            x             xxxx                 |xxxx|                      x  ",
   "                                                      o                                                    x  ",
   "                                                    xxxx                                                   x  ",
   "                                                                                                           x  ",
   "                             x      =       x                                                  xxxx        x  ",
   "                             xxxxxxxxxxxxxxxxxxx                          s                    xxxx        x  ",
   "         @                   x                 xxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!x         xxxx    o   x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
